### ISSUE TITLE
Load viewer map from file

### ISSUE THREAD

**Issue by DennisVargas** [WSUVCapstoneTeam7/SeatMapViewer#5]

**Comment by DennisVargas** [comment]
I found a method in Fabric.js to stop items from being selected gonna attempt this on the viewer.

**Comment by constitutionalFNRC** [comment]
I can be your helper!

**Comment by DennisVargas** [comment]
https://github.com/kangax/fabric.js/issues/586 reveals how to load fabric data but setting it so that it doesn't move. This also allows for the objects to still be selectable.

**Comment by constitutionalFNRC** [comment]
Implemented! See branch "5-load-viewer"

**Comment by DennisVargas** [comment]
We may need to re-evaluate this since I have made significant changes to the format of the json file.
Fabric will load the file directly but everything will be grouped. It will be loader responsibility to ungroup the objects. Unless I write out the file ungrouped and regroup only if the file is loaded on the maker side.

**Comment by constitutionalFNRC** [comment]
Good thing we caught that scalable issue. Will continue on that later.

**Comment by DennisVargas** [comment]
once we load the objects out of the fabCanvas rather than the data object we may be in good shape.

**Comment by constitutionalFNRC** [comment]
Scalability is solved!
